/* Generated by Scriptol */

const fs=require('fs');


// Link View
// (c) 2016-2026 scriptol.com/scriptol.fr
// Free under the GNU GPL 3 License.

var FilesArray=[];
var problem=0;

const empty = function(a) {
  if(a == undefined) return true;
  return a.length == 0;
}

const die=function(message) {
  console.log(message)
  process.exit(1)
}

const ltrim = function(t) {
  if(typeof t === "undefined" || t == false) return "";
	return t.replace(/^\s+/,"");
}

function hasProtocol(theurl) {
   var lowname=ltrim(theurl).toLowerCase();
   if(lowname.slice(0,7)==="http://")  return true;
   if(lowname.slice(0,6)==="ftp://")   return true;
   if(lowname.slice(0,8)==="https://") return true;
   return false;
}

// MERGE - Merge elements of path

function pathMerge(path,filename)   {
      if(path==="") return filename;
      if(filename==="") return path;
      var plc=path.charAt(path.length-1);
      var ffc=filename.charAt(0);
      if((plc==="/")&&(ffc==="/")) {
         return path+filename.slice(1);
      }
      if((plc!="/")&&(ffc!="/")) {
         path+="/";
      }
      return path+filename;
}

function getExtension(path)  {
   var pos=path.lastIndexOf(".");
   if(pos!=-1) {
       return path.slice(pos);
   }
   return "";
}

function addProtocol(domain, protocol = "https://") {
  if (!domain.startsWith("http://") && !domain.startsWith("https://")) {
    return protocol + domain;
  }
  return domain;
}



function filetype(name) {
  var stats = fs.statSync(name);
  if(stats.isDirectory()) return "dir";
  if(stats.isFile()) return "file";
  if(stats.isSocket()) return "socket";
  return "unknown";
}

function parseDir(locdir) {
   var content=fs.readdirSync(locdir);
   var src="";
   var name="";
   if(empty(content)) return;
   for(name of content) {
      src=pathMerge(locdir,name);
      if(filetype(src)==="file") {
         if(name.charAt(0)===".") {
            problem+=1;
            continue;
         }
         FilesArray.push(src);
      }
   }
   for(name of content) {
      if(name.charAt(0)==='.') {
         continue;
      }
      src=pathMerge(locdir,name);
      if(filetype(src)==="dir") {
         parseDir(src);
      }
   }
   return;
}


function start(website, source) {
   FilesArray=[];
   problem=0;   
   console.log("Exploring:")
   console.log("Local dir: " + source)
   website = addProtocol(website)   
   console.log("Website: " + website)

   console.log("Checking links in " + source + " for "+ website);
   parseDir(source);
   if(problem > 0) console.log("Issues : " + problem)
   return 0;
}


/* End */
